// kvsctl-release is the maintainer tool: it builds a release bundle from a
// git checkout, reads image digests and sizes from a registry, and signs
// the manifest kvsctl reads.
package main

import (
	"archive/tar"
	"compress/gzip"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"

	"github.com/MaximeMichaud/KVS-install/cli/internal/manifest"
	"github.com/MaximeMichaud/KVS-install/cli/internal/release"
	"github.com/MaximeMichaud/KVS-install/cli/internal/semver"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	var err error
	switch os.Args[1] {
	case "keygen":
		err = keygen(os.Args[2:])
	case "pubkey":
		err = pubkey(os.Args[2:], os.Stdout)
	case "bundle":
		err = bundle(os.Args[2:])
	case "manifest":
		err = manifestCmd(os.Args[2:])
	case "verify":
		err = verify(os.Args[2:])
	default:
		usage()
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "kvsctl-release:", err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `usage:
  kvsctl-release keygen --out <dir>
      write release.key (PEM, private) and release.pub (base64)

  kvsctl-release pubkey --key release.key
      print the public half of a release key, the line keygen writes to release.pub; the key
      is read the way manifest reads a --key, so what it refuses cannot sign a manifest either

  kvsctl-release bundle --repo <dir> --ref <git ref> --version <v> --out <file.tar.gz> \
      --images <svc=ref|svc@series=ref,...> --digests <svc[@series]=sha256:...,...> [--built <svc,...>]
      package the release files, the compose override pinning the images, and docker/RELEASE;
      every image needs a digest, so the override never pins a tag alone

  kvsctl-release verify --manifest manifest.json --signature manifest.json.sig --pub <base64|id=base64>... [--all]
      check a manifest against its signature file with the given public keys; one match is
      enough, or, with --all, every signature of the file must match one of the keys

  kvsctl-release manifest --key release.key --out <dir> --version <v> --bundle-url <url> --bundle <file.tar.gz> \
      --images <svc=ref|svc@series=ref,...> [--digests <svc[@series]=sha256:...,...>] [--previous manifest.json] \
      [--key <release.key>]... [--key-id <id>]... [--announce-key <id=base64[@YYYY-MM-DD]>]... \
      [--commit <40 hex>] [--notes ..] [--notes-file RELEASE_NOTES.md] [--notes-url ..] [--highlight ..]... \
      [--php 8.1] [--php-series 8.1,8.2,8.3,8.4] [--min-from v] [--kvs-min v] [--kvsctl-min v] \
      [--compose-min 2.19.0] [--database none|migrates] [--one-way] \
      [--cli os-arch=url,...] [--assets <dir>]
      sign the manifest of a release: the stable channel, or the candidate channel for a
      version with a pre-release suffix (26.11.0-rc1)

An image given as service@series=ref is a variant: the release publishes one
image per series and an installation runs the one of its own series. The
axis follows the service: php-fpm and cron vary with the PHP series, filed
under variants.php[series] of the manifest, because the PHP an IonCube site
was encoded for is a property of the instance; mariadb varies with the
MariaDB series, under variants.mariadb[series], because a database keeps
its series until its operator moves it. The compose override reads a
variant image from .env (KVS_PHP_FPM_IMAGE, KVS_CRON_IMAGE,
KVS_MARIADB_IMAGE), where kvsctl writes the one the installation runs. A
plain service=ref does not vary and is pinned directly, as ref@digest.`)
}

// stringList is a flag given more than once.
type stringList []string

func (l *stringList) String() string { return strings.Join(*l, ",") }

func (l *stringList) Set(v string) error {
	*l = append(*l, v)
	return nil
}

// keygen never replaces a key. The private key it writes is the one every
// installed kvsctl ends up trusting, and the second key of a rotation is
// generated by running it again: a directory given twice by mistake must
// not cost the key whose loss means replacing each kvsctl by hand.
func keygen(args []string) error {
	fs := flag.NewFlagSet("keygen", flag.ExitOnError)
	out := fs.String("out", ".", "directory for release.key and release.pub")
	fs.Parse(args)
	keyPath := filepath.Join(*out, "release.key")
	pubPath := filepath.Join(*out, "release.pub")
	for _, path := range []string{keyPath, pubPath} {
		_, err := os.Lstat(path)
		if err == nil {
			return fmt.Errorf("%s already exists: keygen never replaces a key, so give another --out", path)
		}
		if !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return err
	}
	der, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(*out, 0o700); err != nil {
		return err
	}
	if err := writeNewFile(keyPath, pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der}), 0o600); err != nil {
		return err
	}
	if err := writeNewFile(pubPath, []byte(base64.StdEncoding.EncodeToString(pub)+"\n"), 0o644); err != nil {
		return err
	}
	fmt.Printf("private key: %s (keep it out of the repository)\npublic key:  %s\nkey id:      %s\n%s\n",
		keyPath, pubPath, manifest.KeyID(pub), base64.StdEncoding.EncodeToString(pub))
	return nil
}

// writeNewFile writes a file that must not exist yet. The check keygen makes
// first gives the clear message; O_EXCL closes the window between that
// check and the write.
func writeNewFile(path string, data []byte, mode os.FileMode) error {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, mode)
	if err != nil {
		return err
	}
	if _, err := f.Write(data); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}

// pubkey prints the public half of a release key. The signing keys job of
// the release workflow reads each signing secret with it, before any image
// is pushed: the key goes through loadKey, as the --key of the manifest
// command that signs with it later, so a secret the publish job could not
// sign with stops the release there instead.
func pubkey(args []string, out io.Writer) error {
	fs := flag.NewFlagSet("pubkey", flag.ExitOnError)
	keyPath := fs.String("key", "", "the private key, release.key as keygen writes it")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *keyPath == "" || fs.NArg() > 0 {
		return errors.New("pubkey needs --key and nothing else")
	}
	priv, err := loadKey(*keyPath)
	if err != nil {
		return fmt.Errorf("%s: %w", *keyPath, err)
	}
	_, err = fmt.Fprintln(out, base64.StdEncoding.EncodeToString(priv.Public().(ed25519.PublicKey)))
	return err
}

func loadKey(path string) (ed25519.PrivateKey, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, errors.New("release key is not PEM")
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, err
	}
	priv, ok := key.(ed25519.PrivateKey)
	if !ok {
		return nil, errors.New("release key is not Ed25519")
	}
	return priv, nil
}

// signer is one release key with the id its signature carries.
type signer struct {
	id   string
	priv ed25519.PrivateKey
}

// loadSigners reads every --key. A --key-id given at the same position
// names that key; the others are named by the first eight hex characters of
// the sha256 of their public half, which is what kvsctl prints when no key
// it knows verifies.
func loadSigners(paths, ids []string) ([]signer, error) {
	if len(paths) == 0 {
		return nil, errors.New("--key is required")
	}
	if len(ids) > len(paths) {
		return nil, fmt.Errorf("%d --key-id for %d --key: they pair by position", len(ids), len(paths))
	}
	var out []signer
	seen := map[string]bool{}
	for i, path := range paths {
		priv, err := loadKey(path)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		id := ""
		if i < len(ids) {
			id = strings.TrimSpace(ids[i])
		}
		if id == "" {
			id = manifest.KeyID(priv.Public().(ed25519.PublicKey))
		}
		if seen[id] {
			return nil, fmt.Errorf("key id %s is used twice", id)
		}
		seen[id] = true
		out = append(out, signer{id: id, priv: priv})
	}
	return out, nil
}

// signManifest writes the signature file: a JSON list with one entry per
// key, so a rotation release is signed by the outgoing key and the incoming
// one at once. A single key writes the same form.
func signManifest(raw []byte, signers []signer) ([]byte, error) {
	sigs := make([]manifest.Signature, 0, len(signers))
	for _, s := range signers {
		sigs = append(sigs, manifest.Signature{
			KeyID: s.id,
			Alg:   manifest.AlgEd25519,
			Sig:   base64.StdEncoding.EncodeToString(ed25519.Sign(s.priv, raw)),
		})
	}
	file, err := json.MarshalIndent(sigs, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(file, '\n'), nil
}

// imageSpec is one --images entry: a service, the variant axis and value
// when the image depends on a series the installation runs, and the image
// reference.
type imageSpec struct {
	Service string
	// Axis is the variant axis, manifest.VariantPHP or VariantMariaDB, and
	// Series the value on it; both are empty for an image every
	// installation runs.
	Axis   string
	Series string
	Ref    string
}

// Key is how an image is named in --digests and in the maps below.
func (s imageSpec) Key() string { return variantKey(s.Service, s.Series) }

func variantKey(service, series string) string {
	if series == "" {
		return service
	}
	return service + "@" + series
}

// variantAxes are the services published once per series, and the axis
// each one varies by. php-fpm and cron are built on the PHP base of the
// series an IonCube site was encoded for; mariadb runs the series whose data
// files the database holds. Any other service has one image per release.
var variantAxes = map[string]string{
	"php-fpm": manifest.VariantPHP,
	"cron":    manifest.VariantPHP,
	"mariadb": manifest.VariantMariaDB,
}

// seriesRe is a PHP or MariaDB series: major.minor, as "8.1" or "11.8".
var seriesRe = regexp.MustCompile(`^[0-9]+\.[0-9]+$`)

// fields splits a list written with commas, spaces or newlines, so a spec
// file produced by a workflow can be passed as it is.
func fields(spec string) []string {
	return strings.FieldsFunc(spec, func(r rune) bool { return r == ',' || unicode.IsSpace(r) })
}

// parseImages reads "nginx=ref,php-fpm@8.1=ref,mariadb@11.8=ref": a plain
// entry is an image every instance runs, an entry with a series is
// published once per series, on the axis its service varies by.
var composeServiceRe = regexp.MustCompile(`^  ([A-Za-z0-9][A-Za-z0-9_.-]*):[ \t]*(#.*)?$`)

// composeServices lists the services of a compose file: the keys indented
// by two spaces under the top-level services key, the way
// docker/docker-compose.yml is written.
func composeServices(text string) []string {
	var names []string
	inServices := false
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimRight(line, "\r")
		if strings.TrimSpace(line) == "" || strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		if !strings.HasPrefix(line, " ") {
			inServices = strings.HasPrefix(line, "services:")
			continue
		}
		if m := composeServiceRe.FindStringSubmatch(line); inServices && m != nil {
			names = append(names, m[1])
		}
	}
	return names
}

// checkCoverage wants an image for every service of the compose file and
// no image for a service it does not hold.
func checkCoverage(services []string, specs []imageSpec) error {
	named := map[string]bool{}
	for _, spec := range specs {
		named[spec.Service] = true
	}
	inCompose := map[string]bool{}
	var missing []string
	for _, service := range services {
		inCompose[service] = true
		if !named[service] {
			missing = append(missing, service)
		}
	}
	var extra []string
	for service := range named {
		if !inCompose[service] {
			extra = append(extra, service)
		}
	}
	sort.Strings(extra)
	switch {
	case len(services) == 0:
		return errors.New("docker/docker-compose.yml lists no service")
	case len(missing) > 0:
		return fmt.Errorf("the image list names no image for %s of docker/docker-compose.yml", strings.Join(missing, ", "))
	case len(extra) > 0:
		return fmt.Errorf("the image list names %s, which docker/docker-compose.yml does not run", strings.Join(extra, ", "))
	}
	return nil
}

func parseImages(spec string) ([]imageSpec, error) {
	var out []imageSpec
	seen := map[string]bool{}
	varies := map[string]bool{}
	plain := map[string]bool{}
	for _, item := range fields(spec) {
		left, ref, ok := strings.Cut(item, "=")
		if !ok || ref == "" {
			return nil, fmt.Errorf("image %q is not service=ref or service@series=ref", item)
		}
		service, series, hasSeries := strings.Cut(left, "@")
		if service == "" || (hasSeries && series == "") {
			return nil, fmt.Errorf("image %q is not service=ref or service@series=ref", item)
		}
		axis := ""
		if hasSeries {
			axis = variantAxes[service]
			if axis == "" {
				return nil, fmt.Errorf("image %q: %s has one image per release, only %s vary by series", item, service, strings.Join(sortedKeys(variantAxes), ", "))
			}
			if !seriesRe.MatchString(series) {
				return nil, fmt.Errorf("image %q: %q is not a %s series (major.minor)", item, series, manifest.AxisLabel(axis))
			}
		}
		key := variantKey(service, series)
		if seen[key] {
			return nil, fmt.Errorf("image %s is given twice", key)
		}
		seen[key] = true
		if hasSeries {
			varies[service] = true
		} else {
			plain[service] = true
		}
		if varies[service] && plain[service] {
			return nil, fmt.Errorf("image %s is given both with and without a series", service)
		}
		out = append(out, imageSpec{Service: service, Axis: axis, Series: series, Ref: ref})
	}
	return out, nil
}

// parseDigests reads "nginx=sha256:...,php-fpm@8.1=sha256:...", what the
// build step of the workflow reported for each image. The workflow writes
// the non-varying ones as "nginx@=sha256:...", which reads the same.
func parseDigests(spec string) (map[string]string, error) {
	out := map[string]string{}
	for _, item := range fields(spec) {
		left, digest, ok := strings.Cut(item, "=")
		if !ok {
			return nil, fmt.Errorf("digest %q is not service[@series]=sha256:...", item)
		}
		service, series, _ := strings.Cut(left, "@")
		if service == "" || !strings.HasPrefix(digest, "sha256:") {
			return nil, fmt.Errorf("digest %q is not service[@series]=sha256:...", item)
		}
		out[variantKey(service, series)] = digest
	}
	return out, nil
}

func splitList(spec string) []string {
	return fields(spec)
}

func bundle(args []string) error {
	fs := flag.NewFlagSet("bundle", flag.ExitOnError)
	repo := fs.String("repo", ".", "git checkout")
	ref := fs.String("ref", "HEAD", "git ref to package")
	version := fs.String("version", "", "release version")
	imageSpecs := fs.String("images", "", "service=ref or service@series=ref pairs pinned by docker-compose.release.yml")
	digestSpec := fs.String("digests", "", "service[@series]=sha256:... pairs, one for every image of --images; the override pins each image to its digest")
	builtSpec := fs.String("built", strings.Join(builtByDefault, ","), "services the base compose file builds, whose build section the override has to clear")
	out := fs.String("out", "", "bundle file (.tar.gz)")
	fs.Parse(args)
	if *version == "" || *out == "" {
		return errors.New("--version and --out are required")
	}
	if _, err := semver.Parse(*version); err != nil {
		return err
	}
	specs, err := parseImages(*imageSpecs)
	if err != nil {
		return err
	}
	digests, err := parseDigests(*digestSpec)
	if err != nil {
		return err
	}
	pins, err := pinnedRefs(specs, digests)
	if err != nil {
		return err
	}
	built := map[string]bool{}
	for _, service := range splitList(*builtSpec) {
		built[service] = true
	}
	// The override pins what the image list names, and nothing else: a
	// service of the compose file it leaves out would be built on the
	// server or run a moving tag, and a name the compose file does not hold
	// would add a service to the stack.
	composeFile, err := exec.Command("git", "-C", *repo, "show", *ref+":docker/docker-compose.yml").Output()
	if err != nil {
		return fmt.Errorf("git show docker/docker-compose.yml: %w", err)
	}
	if err := checkCoverage(composeServices(string(composeFile)), specs); err != nil {
		return err
	}
	cmd := exec.Command("git", append([]string{"-C", *repo, "ls-tree", "-r", "-z", *ref, "--"}, release.Paths...)...)
	listing, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("git ls-tree: %w", err)
	}
	// A release ships regular files: kvsctl lays a bundle down file by file,
	// and a symbolic link or a submodule would arrive as a file holding a
	// path, or not at all.
	var files []string
	modes := map[string]int64{}
	for _, entry := range strings.Split(string(listing), "\x00") {
		if entry == "" {
			continue
		}
		meta, name, found := strings.Cut(entry, "\t")
		fields := strings.Fields(meta)
		if !found || len(fields) != 3 {
			return fmt.Errorf("git ls-tree: unexpected entry %q", entry)
		}
		switch fields[0] {
		case "100644":
			modes[name] = 0o644
		case "100755":
			modes[name] = 0o755
		default:
			return fmt.Errorf("%s has git mode %s: a release ships regular files only", name, fields[0])
		}
		files = append(files, name)
	}
	sort.Strings(files)
	// Every member carries the time of the commit and the gzip header none,
	// so two bundles of one ref are the same bytes: anyone can build one
	// from the tag and compare it with the sha256 the manifest signs.
	when, err := exec.Command("git", "-C", *repo, "log", "-1", "--format=%ct", *ref).Output()
	if err != nil {
		return fmt.Errorf("git log %s: %w", *ref, err)
	}
	seconds, err := strconv.ParseInt(strings.TrimSpace(string(when)), 10, 64)
	if err != nil {
		return fmt.Errorf("commit time of %s: %w", *ref, err)
	}
	stamp := time.Unix(seconds, 0).UTC()
	f, err := os.Create(*out)
	if err != nil {
		return err
	}
	gz := gzip.NewWriter(f)
	tw := tar.NewWriter(gz)
	for _, name := range files {
		content, err := exec.Command("git", "-C", *repo, "show", *ref+":"+name).Output()
		if err != nil {
			return fmt.Errorf("git show %s: %w", name, err)
		}
		if err := tw.WriteHeader(&tar.Header{Name: name, Mode: modes[name], Size: int64(len(content)), ModTime: stamp, Typeflag: tar.TypeReg}); err != nil {
			return err
		}
		if _, err := tw.Write(content); err != nil {
			return err
		}
	}
	// The version the files come from, readable without kvsctl and without
	// the state file: docker/RELEASE is what an operator reads on the
	// server to know which release laid these files down.
	added := map[string]string{"docker/RELEASE": *version + "\n"}
	if len(specs) > 0 {
		added["docker/"+releaseOverride] = renderOverride(*version, specs, pins, built)
	}
	for _, name := range sortedKeys(added) {
		content := added[name]
		if err := tw.WriteHeader(&tar.Header{Name: name, Mode: 0o644, Size: int64(len(content)), ModTime: stamp, Typeflag: tar.TypeReg}); err != nil {
			return err
		}
		if _, err := tw.Write([]byte(content)); err != nil {
			return err
		}
	}
	if err := tw.Close(); err != nil {
		return err
	}
	if err := gz.Close(); err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	sum, size, err := fileSum(*out)
	if err != nil {
		return err
	}
	fmt.Printf("%s: %d files, %d bytes, sha256 %s\n", *out, len(files)+len(added), size, sum)
	return nil
}

// releaseOverride is the compose file the bundle carries; kvsctl adds it to
// COMPOSE_FILE when it applies the release.
const releaseOverride = "docker-compose.release.yml"

// builtByDefault are the services docker/docker-compose.yml builds on the
// server. The override clears their build section, or compose would build
// them again as soon as the pinned image is missing from the engine.
var builtByDefault = []string{"nginx", "php-fpm", "cron", "kvs-init", "manticore"}

// renderOverride writes the compose override that pins the images of a
// release. pins holds ref@digest for every image (pinnedRefs). A service
// whose image varies with a series reads it from .env, where kvsctl writes
// the image of the series the instance runs.
func renderOverride(version string, specs []imageSpec, pins map[string]string, built map[string]bool) string {
	var order []string
	image := map[string]string{}
	varies := map[string]bool{}
	for _, s := range specs {
		if _, seen := image[s.Service]; !seen {
			order = append(order, s.Service)
			image[s.Service] = pins[s.Key()]
		}
		if s.Series != "" {
			varies[s.Service] = true
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by kvsctl-release for stack %s: the images this release runs.\n", version)
	b.WriteString(`#
# kvsctl adds this file to COMPOSE_FILE, so every "docker compose" command of
# the installation, by hand or from the scripts, runs these images instead of
# building the services on the server. "build: !reset null" removes the build
# section the base compose file carries for them, which Docker Compose does
# from 2.19.0 on (2.18 reads it as a build from a directory named null): that
# is the version requires.compose_min names in the manifest. Every image is
# written as ref@sha256:..., which is that exact image, so a tag pushed again
# later cannot change what runs.
`)
	if len(varies) > 0 {
		b.WriteString(`#
# The services whose image depends on a series the installation runs read it
# from .env, where kvsctl writes the image of that series as ref@sha256:...:
# php-fpm and cron follow the PHP series an IonCube encoded site needs, and
# mariadb the MariaDB series its data files belong to. Both are properties of
# the instance, not of the release, so one override serves every published
# series. When the key is missing, Compose stops and prints the text after
# ":?" with the name of the key.
`)
	}
	b.WriteString("services:\n")
	for _, service := range order {
		fmt.Fprintf(&b, "  %s:\n", service)
		if built[service] {
			b.WriteString("    build: !reset null\n")
		}
		if varies[service] {
			fmt.Fprintf(&b, "    image: %q\n", "${"+envVar(service)+":?"+missingImageMessage+"}")
			continue
		}
		fmt.Fprintf(&b, "    image: %q\n", image[service])
	}
	return b.String()
}

// missingImageMessage is what Compose prints after "required variable
// KVS_..._IMAGE is missing a value:" when .env lacks the image of a variant
// service. A plain ${KVS_..._IMAGE} would only warn that the variable is
// blank and then fail on a service that "has neither an image nor a build
// context", which names neither the key nor who writes it. The message
// holds no closing brace, which would end the variable.
const missingImageMessage = "kvsctl writes it to .env when it applies a release"

// pinnedRefs is the reference of every image as ref@digest, keyed like
// --digests: the digest a reference already carries, or the one --digests
// gives. An image without a digest is an error, because an override that
// pins a tag alone runs whatever the tag points at on the day of the pull,
// and so is a digest that names no image of the list.
func pinnedRefs(specs []imageSpec, digests map[string]string) (map[string]string, error) {
	out := map[string]string{}
	unused := map[string]bool{}
	for key := range digests {
		unused[key] = true
	}
	for _, s := range specs {
		key := s.Key()
		delete(unused, key)
		given := digests[key]
		_, inRef, hasDigest := strings.Cut(s.Ref, "@")
		switch {
		case hasDigest && !strings.HasPrefix(inRef, "sha256:"):
			return nil, fmt.Errorf("image %s: %s does not end with a sha256 digest", key, s.Ref)
		case hasDigest && given != "" && given != inRef:
			return nil, fmt.Errorf("image %s: the reference carries %s and --digests gives %s", key, inRef, given)
		case hasDigest:
			out[key] = s.Ref
		case given != "":
			out[key] = s.Ref + "@" + given
		default:
			return nil, fmt.Errorf("image %s has no digest: the override would pin %s by its tag alone; pass its digest with --digests", key, s.Ref)
		}
	}
	if len(unused) > 0 {
		return nil, fmt.Errorf("--digests names %s, which --images does not list", strings.Join(sortedKeys(unused), ", "))
	}
	return out, nil
}

// envVar is the .env variable carrying the image of a service that varies
// with a series: KVS_PHP_FPM_IMAGE for php-fpm, KVS_CRON_IMAGE for cron,
// KVS_MARIADB_IMAGE for mariadb.
func envVar(service string) string {
	return "KVS_" + strings.NewReplacer("-", "_", ".", "_").Replace(strings.ToUpper(service)) + "_IMAGE"
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func fileSum(path string) (string, int64, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", 0, err
	}
	defer f.Close()
	hash := sha256.New()
	n, err := io.Copy(hash, f)
	if err != nil {
		return "", 0, err
	}
	return hex.EncodeToString(hash.Sum(nil)), n, nil
}

// bundleStamp reads the time every member of the bundle carries, which
// kvsctl-release bundle sets to the time of the release commit, and which
// dates the release in the manifest. kvsctl refuses to lay a release over
// an adopted git checkout whose commit is newer than that date, since that
// would take its files back; the day the manifest is signed would let
// through every commit made between the tag and an approved or re-run
// publish job. The bundle has to be the one of this version, since the
// manifest signs its checksum too.
func bundleStamp(path, version string) (time.Time, error) {
	f, err := os.Open(path)
	if err != nil {
		return time.Time{}, err
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		return time.Time{}, fmt.Errorf("bundle %s is not a .tar.gz: %w", path, err)
	}
	tr := tar.NewReader(gz)
	var stamp time.Time
	members := 0
	released, hasRelease := "", false
	for {
		h, err := tr.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return time.Time{}, fmt.Errorf("bundle %s: %w", path, err)
		}
		if members == 0 {
			stamp = h.ModTime
		} else if !h.ModTime.Equal(stamp) {
			return time.Time{}, fmt.Errorf("bundle %s: %s carries %s and the members before it %s; kvsctl-release bundle gives every member the time of the release commit, which dates the release",
				path, h.Name, h.ModTime.UTC().Format(time.RFC3339), stamp.UTC().Format(time.RFC3339))
		}
		members++
		if h.Name == "docker/RELEASE" {
			data, err := io.ReadAll(io.LimitReader(tr, 1024))
			if err != nil {
				return time.Time{}, fmt.Errorf("bundle %s: %w", path, err)
			}
			released, hasRelease = strings.TrimSpace(string(data)), true
		}
	}
	switch {
	case members == 0:
		return time.Time{}, fmt.Errorf("bundle %s holds no file", path)
	case !hasRelease:
		return time.Time{}, fmt.Errorf("bundle %s holds no docker/RELEASE: build it with kvsctl-release bundle", path)
	case released != version:
		return time.Time{}, fmt.Errorf("bundle %s is the bundle of %s, not of %s: its docker/RELEASE says so", path, released, version)
	}
	return stamp.UTC(), nil
}

// firstParagraph reduces a release notes file to the one line the manifest
// carries: the first block of text, markdown headings skipped and the lines
// joined. The rest of the file stays where it belongs, behind --notes-url,
// because the manifest is fetched on every status check.
func firstParagraph(text string) string {
	var out []string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			if len(out) > 0 {
				break
			}
			continue
		}
		if len(out) == 0 && strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	if len(out) > 0 {
		out[0] = strings.TrimPrefix(strings.TrimPrefix(out[0], "- "), "* ")
	}
	return strings.Join(strings.Fields(strings.Join(out, " ")), " ")
}

// parseAnnouncedKeys reads "ID=BASE64" or "ID=BASE64@2026-11-01", where ID
// is the key id keygen prints. The list is information for the operator: a
// manifest cannot introduce the key that signs it, so kvsctl only reports
// that a new key is coming and update-cli brings the binary that trusts it.
// kvsctl stays quiet about an announced key whose id is the id of a key it
// embeds, which is why the id has to be the one derived from the key: any
// other name would keep warning on the binaries that already trust it.
func parseAnnouncedKeys(specs []string) ([]manifest.Key, error) {
	var out []manifest.Key
	for _, spec := range specs {
		id, rest, ok := strings.Cut(strings.TrimSpace(spec), "=")
		if !ok || id == "" || rest == "" {
			return nil, fmt.Errorf("announced key %q is not id=base64[@YYYY-MM-DD]", spec)
		}
		pub, validFrom, _ := strings.Cut(rest, "@")
		keys, err := manifest.ParseKeys([]string{pub})
		if err != nil {
			return nil, fmt.Errorf("announced key %s: %w", id, err)
		}
		if derived := manifest.KeyID(keys[0]); id != derived {
			return nil, fmt.Errorf("announced key %s: the id of this key is %s (keygen prints it), and kvsctl knows a key by that id", id, derived)
		}
		if validFrom != "" {
			if _, err := time.Parse("2006-01-02", validFrom); err != nil {
				return nil, fmt.Errorf("announced key %s: %q is not a YYYY-MM-DD date", id, validFrom)
			}
		}
		out = append(out, manifest.Key{ID: id, Pub: pub, ValidFrom: validFrom})
	}
	return out, nil
}

func manifestCmd(args []string) error {
	fs := flag.NewFlagSet("manifest", flag.ExitOnError)
	var keyPaths, keyIDs, highlights, announce stringList
	fs.Var(&keyPaths, "key", "release.key; repeat it so a rotation release is signed by the outgoing and the incoming key")
	fs.Var(&keyIDs, "key-id", "id of the --key at the same position; derived from the key when absent")
	fs.Var(&highlights, "highlight", "one short line for the confirmation screen; at most three")
	fs.Var(&announce, "announce-key", "id=base64[@YYYY-MM-DD] of a key a later release will sign with alone, id being the key id keygen prints; it signs this release too, as a --key, and it replaces the keys --previous announced")
	out := fs.String("out", ".", "directory receiving manifest.json and manifest.json.sig")
	version := fs.String("version", "", "release version")
	commit := fs.String("commit", "", "the git commit the release is cut from, its full hexadecimal id")
	notes := fs.String("notes", "", "release notes, one line")
	notesFile := fs.String("notes-file", "", "file whose first paragraph becomes the one line of notes, ignored when --notes is given")
	notesURL := fs.String("notes-url", "", "where the full changelog of this release lives")
	bundleURL := fs.String("bundle-url", "", "where kvsctl downloads the bundle")
	bundlePath := fs.String("bundle", "", "the bundle kvsctl-release bundle wrote, for its checksum and for the time of the release commit its files carry, which dates the release")
	imageSpecs := fs.String("images", "", "service=ref or service@series=ref pairs; digests and sizes are read from the registry")
	digestSpec := fs.String("digests", "", "service[@series]=sha256:... the build reported; a digest the registry does not confirm is an error")
	previous := fs.String("previous", "", "existing manifest.json to extend")
	php := fs.String("php", "", "default PHP series of the release, one it publishes images for; the lowest published series when absent")
	phpSeries := fs.String("php-series", "", "every PHP series the release publishes images for, checked against --images; the published ones when absent")
	minFrom := fs.String("min-from", "", "oldest version that may upgrade directly, a release the manifest lists")
	kvsMin := fs.String("kvs-min", "", "oldest KVS version supported")
	kvsctlMin := fs.String("kvsctl-min", "", "oldest kvsctl that may install the release, at most the release itself; check and upgrade on an older one ask for update-cli first, and a candidate of that version (26.11.0-rc1 for 26.11.0) asks for its own kvsctl")
	composeMin := fs.String("compose-min", "", "oldest Docker Compose that reads the override, 2.19.0 for build: !reset null")
	database := fs.String("database", "", "none or migrates")
	oneWay := fs.Bool("one-way", false, "the release cannot be undone by restarting the previous images: the rollback recreates the MariaDB data directory and replays the dump, and --skip-backup becomes an error")
	cliSpec := fs.String("cli", "", "os-arch=url pairs of kvsctl binaries; their sha256 comes from --assets or from url+.sha256")
	assets := fs.String("assets", "", "directory holding the files named in --cli (by their base name) before they are published; its SHA256SUMS, when there is one, must list the same sums")
	fs.Parse(args)
	if len(keyPaths) == 0 || *version == "" || *bundleURL == "" || *bundlePath == "" {
		return errors.New("--key, --version, --bundle-url and --bundle are required")
	}
	released, err := semver.Parse(*version)
	if err != nil {
		return err
	}
	if *commit != "" && !commitRe.MatchString(*commit) {
		return fmt.Errorf("--commit %q is not a full git commit id (40 hexadecimal characters, as git rev-parse prints it)", *commit)
	}
	if err := checkRequires(*version, *minFrom, *kvsMin, *composeMin, *database); err != nil {
		return err
	}
	needsKvsctl, err := kvsctlMinimum(*kvsctlMin, released)
	if err != nil {
		return err
	}
	if err := checkHighlights(highlights); err != nil {
		return err
	}
	signers, err := loadSigners(keyPaths, keyIDs)
	if err != nil {
		return err
	}
	announced, err := parseAnnouncedKeys(announce)
	if err != nil {
		return err
	}
	if err := checkAnnouncedSign(announced, signers); err != nil {
		return err
	}
	m := &manifest.Manifest{Schema: manifest.Schema}
	if *previous != "" {
		data, err := os.ReadFile(*previous)
		if err != nil {
			return err
		}
		// The releases it lists are written back as they are decoded, the
		// requires.kvsctl_min each one was signed with included.
		m, err = manifest.Parse(data)
		if err != nil {
			return err
		}
		// A release extends the stable list, never the list of a candidate,
		// which would offer the candidate to every installation as the
		// latest stable release.
		if m.Channel != channelStable {
			return fmt.Errorf("--previous %s is a manifest of channel %q: a release extends the stable list, the manifest of the latest stable release (channel %s)", *previous, m.Channel, channelStable)
		}
		m.Schema = manifest.Schema
	}
	m.Channel = channelOf(released)
	if *minFrom != "" {
		if err := checkStop(*minFrom, *version, m.Releases); err != nil {
			return err
		}
	}
	// The announcement is what this run says, never a leftover of the
	// previous manifest: the release that stops announcing a key, once it
	// signs, simply passes no --announce-key.
	m.Keys = announced
	sum, size, err := fileSum(*bundlePath)
	if err != nil {
		return err
	}
	stamp, err := bundleStamp(*bundlePath, *version)
	if err != nil {
		return err
	}
	text := *notes
	if text == "" && *notesFile != "" {
		data, err := os.ReadFile(*notesFile)
		if err != nil {
			return err
		}
		text = firstParagraph(string(data))
	}
	rel := manifest.Release{
		Version:    *version,
		Date:       stamp.Format(time.RFC3339),
		Commit:     *commit,
		Notes:      text,
		NotesURL:   *notesURL,
		Highlights: highlights,
		Bundle:     manifest.Asset{URL: *bundleURL, SHA256: sum, Size: size},
		Requires: manifest.Requires{
			MinFrom:    *minFrom,
			PHP:        *php,
			KVSMin:     *kvsMin,
			ComposeMin: *composeMin,
			KvsctlMin:  needsKvsctl,
		},
		Database: *database,
		OneWay:   *oneWay,
	}
	specs, err := parseImages(*imageSpecs)
	if err != nil {
		return err
	}
	digests, err := parseDigests(*digestSpec)
	if err != nil {
		return err
	}
	for _, s := range specs {
		digest, imageSize, layers, err := registryDigest(s.Ref)
		if err != nil {
			return fmt.Errorf("%s: %w", s.Ref, err)
		}
		if want, ok := digests[s.Key()]; ok {
			if want != digest {
				return fmt.Errorf("%s: the build reported %s and the registry answers %s", s.Key(), want, digest)
			}
			delete(digests, s.Key())
		}
		img := manifest.Image{Service: s.Service, Ref: s.Ref, Digest: digest, Size: imageSize, Layers: layers}
		if s.Axis == "" {
			rel.Images = append(rel.Images, img)
		} else {
			if rel.Variants == nil {
				rel.Variants = map[string]map[string][]manifest.Image{}
			}
			if rel.Variants[s.Axis] == nil {
				rel.Variants[s.Axis] = map[string][]manifest.Image{}
			}
			rel.Variants[s.Axis][s.Series] = append(rel.Variants[s.Axis][s.Series], img)
		}
		fmt.Printf("%-18s %s %s %d bytes, %d layers\n", s.Key(), s.Ref, digest, imageSize, len(layers))
	}
	if len(digests) > 0 {
		return fmt.Errorf("--digests names %s, which --images does not build", strings.Join(sortedKeys(digests), ", "))
	}
	published := rel.Series()
	if listed := splitList(*phpSeries); len(listed) > 0 {
		if err := checkSeries(listed, published); err != nil {
			return err
		}
	}
	rel.Requires.PHPSeries = published
	switch {
	case rel.Requires.PHP == "" && len(published) > 0:
		rel.Requires.PHP = published[0]
	case rel.Requires.PHP != "" && len(published) > 0 && !slicesContains(published, rel.Requires.PHP):
		return fmt.Errorf("--php %s is not a series the release publishes images for (%s)", rel.Requires.PHP, strings.Join(published, ", "))
	}
	if *cliSpec != "" {
		rel.CLI = map[string]manifest.Asset{}
		listed, err := publishedSums(*assets)
		if err != nil {
			return err
		}
		for _, item := range fields(*cliSpec) {
			platform, url, ok := strings.Cut(item, "=")
			if !ok {
				return fmt.Errorf("cli %q is not os-arch=url", item)
			}
			sum, size, err := assetSum(url, *assets)
			if err != nil {
				return err
			}
			// The release publishes SHA256SUMS beside the binaries for a
			// download checked by hand, and update-cli checks the sum the
			// manifest signs: both have to name the same file.
			if listed != nil {
				name := filepath.Base(url)
				switch want, ok := listed[name]; {
				case !ok:
					return fmt.Errorf("%s is not listed in %s", name, filepath.Join(*assets, sumsFile))
				case want != sum:
					return fmt.Errorf("%s: %s lists %s and the file hashes to %s", name, filepath.Join(*assets, sumsFile), want, sum)
				}
			}
			rel.CLI[platform] = manifest.Asset{URL: url, SHA256: sum, Size: size}
		}
	}
	var releases []manifest.Release
	for _, r := range m.Releases {
		if r.Version != rel.Version {
			releases = append(releases, r)
		}
	}
	m.Releases = append(releases, rel)
	sort.SliceStable(m.Releases, func(i, j int) bool { return semver.Less(m.Releases[j].Version, m.Releases[i].Version) })
	m.Updated = time.Now().UTC().Format(time.RFC3339)
	if needsKvsctl != "" {
		fmt.Printf("%-18s kvsctl %s or newer\n", "kvsctl_min", needsKvsctl)
	}
	raw, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	if _, err := manifest.Parse(raw); err != nil {
		return err
	}
	if err := checkSize(len(raw), len(m.Releases)); err != nil {
		return err
	}
	if err := os.MkdirAll(*out, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(*out, "manifest.json"), raw, 0o644); err != nil {
		return err
	}
	sig, err := signManifest(raw, signers)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(*out, "manifest.json.sig"), sig, 0o644); err != nil {
		return err
	}
	var ids []string
	for _, s := range signers {
		ids = append(ids, s.id)
	}
	fmt.Printf("%s: %d releases, latest %s, channel %s, signed by %s\n", filepath.Join(*out, "manifest.json"), len(m.Releases), rel.Version, m.Channel, strings.Join(ids, ", "))
	return nil
}

// The channels a manifest is signed into, as kvsctl reads them.
const (
	channelStable    = "stable"
	channelCandidate = "candidate"
)

// channelOf is the channel of the manifest that publishes a release: the
// candidate channel for a version with a pre-release suffix (26.11.0-rc1),
// the stable one otherwise. The manifest of a candidate is the stable list
// of the day with the candidate added, signed with the same key, so its
// channel is what keeps it from passing for the stable list: kvsctl reads
// the stable channel alone from the URL of the latest release.
func channelOf(v semver.Version) string {
	if v.Pre != "" {
		return channelCandidate
	}
	return channelStable
}

// kvsctlMinimum is the requires.kvsctl_min a release is signed with, from
// --kvsctl-min. update-cli installs the kvsctl a release ships, so a
// minimum newer than the release names a kvsctl no manifest offers, and no
// installation could ever install the release: that is refused. A candidate
// is the one exception. .github/release.env names the release the
// candidates lead to, 26.11.0, and 26.11.0-rc1 is cut with the same file,
// so the manifest of the candidate asks for the kvsctl of the candidate,
// the only one of that version so far.
func kvsctlMinimum(minimum string, version semver.Version) (string, error) {
	if minimum == "" {
		return "", nil
	}
	floor, err := semver.Parse(minimum)
	if err != nil {
		return "", fmt.Errorf("--kvsctl-min: %w", err)
	}
	if semver.Compare(floor, version) <= 0 {
		return floor.String(), nil
	}
	leadsTo := semver.Version{Major: version.Major, Minor: version.Minor, Patch: version.Patch}
	if version.Pre != "" && semver.Compare(floor, leadsTo) == 0 {
		return version.String(), nil
	}
	return "", fmt.Errorf("--kvsctl-min %s is newer than the release %s: update-cli installs the kvsctl a release ships, so no installation could get a kvsctl that may install it", minimum, version)
}

// checkHighlights wants at most three highlights, each one line: kvsctl
// prints every highlight as a line of the confirmation screen.
func checkHighlights(highlights []string) error {
	if len(highlights) > 3 {
		return fmt.Errorf("%d highlights: at most three fit the confirmation screen, the rest belongs behind --notes-url", len(highlights))
	}
	for _, h := range highlights {
		if strings.TrimSpace(h) == "" {
			return errors.New("a --highlight is empty: kvsctl would print an empty line on the confirmation screen")
		}
		if strings.ContainsAny(h, "\r\n") {
			return fmt.Errorf("--highlight %q holds more than one line: kvsctl prints each highlight as one line of the confirmation screen", h)
		}
	}
	return nil
}

// checkSeries wants --php-series to name exactly the PHP series the
// release publishes images for. requires.php_series is what kvsctl tells
// an installation the release runs: a series missing from it hides images
// that were built, and a series without images is offered to
// installations that then find nothing to pull.
func checkSeries(listed, published []string) error {
	for _, s := range published {
		if !slicesContains(listed, s) {
			return fmt.Errorf("the release publishes images for PHP %s, which --php-series does not list", s)
		}
	}
	for _, s := range listed {
		if !slicesContains(published, s) {
			return fmt.Errorf("--php-series lists PHP %s, for which the release publishes no image", s)
		}
	}
	return nil
}

// commitRe is a full git commit id, as the manifest accepts it: 40
// hexadecimal characters, or 64 in a repository using SHA-256.
var commitRe = regexp.MustCompile(`^[0-9a-f]{40}([0-9a-f]{24})?$`)

// checkRequires refuses what kvsctl could not use. A minimum that is not a
// version never blocks anything on the client, which would turn a typo in
// .github/release.env into a missing guard, and a database value other than
// the two kvsctl knows would be signed and then read as "none".
func checkRequires(version, minFrom, kvsMin, composeMin, database string) error {
	for _, v := range []struct{ flag, value string }{
		{"--min-from", minFrom},
		{"--kvs-min", kvsMin},
		{"--compose-min", composeMin},
	} {
		if v.value == "" {
			continue
		}
		if _, err := semver.Parse(v.value); err != nil {
			return fmt.Errorf("%s: %w", v.flag, err)
		}
	}
	if minFrom != "" && !semver.Less(minFrom, version) {
		return fmt.Errorf("--min-from %s is not older than the release %s: no installation could upgrade to it", minFrom, version)
	}
	switch database {
	case "", "none", "migrates":
	default:
		return fmt.Errorf("--database is %q, which is neither none nor migrates", database)
	}
	return nil
}

// checkStop wants the stop a release names to be a release of the manifest
// it is signed into. kvsctl sends every older installation through that
// version first, and a version no manifest lists can never be installed, so
// those installations would be blocked by this manifest and by every later
// one, which carries the release unchanged. releases are the ones the
// manifest already holds, newest first.
func checkStop(minFrom, version string, releases []manifest.Release) error {
	var older []string
	for _, r := range releases {
		if r.Version == minFrom {
			return nil
		}
		if semver.Less(r.Version, version) {
			older = append(older, r.Version)
		}
	}
	if len(older) == 0 {
		return fmt.Errorf("--min-from %s names no release of the manifest, which holds none older than %s (is --previous missing?): no installation could go through it", minFrom, version)
	}
	const shown = 10
	list := strings.Join(older[:min(len(older), shown)], ", ")
	if len(older) > shown {
		list += fmt.Sprintf(" and %d older", len(older)-shown)
	}
	return fmt.Errorf("--min-from %s names no release of the manifest, so no installation could go through it; the releases older than %s are %s", minFrom, version, list)
}

// checkAnnouncedSign wants every announced key among the keys that sign. The
// release that switches to a new key checks the manifest it extends with
// that key alone, so an announcing release signed without it would only be
// found out at the switch, after weeks of releases, with nothing to do but
// go back to the announcement with both keys.
func checkAnnouncedSign(announced []manifest.Key, signers []signer) error {
	for _, k := range announced {
		keys, err := manifest.ParseKeys([]string{k.Pub})
		if err != nil {
			return fmt.Errorf("announced key %s: %w", k.ID, err)
		}
		signs := false
		for _, s := range signers {
			if keys[0].Equal(s.priv.Public()) {
				signs = true
			}
		}
		if !signs {
			return fmt.Errorf("--announce-key %s: no --key is that key, and the release that switches to it checks this manifest with that key alone: "+
				"sign with both keys, the new one as another --key (the secret KVSCTL_RELEASE_KEY_NEXT of the release workflow)", k.ID)
		}
	}
	return nil
}

// maxManifest is the largest manifest kvsctl reads: its read stops there
// and refuses a longer file (cli/internal/manifest). It stays at the 8 MiB
// of the first kvsctl releases even once a newer one reads more: an
// installation keeps its kvsctl until update-cli replaces it, and update-cli
// reads the manifest first. The manifest lists every release, so it only
// grows, by about 76 kB per release of the current stack: about 110
// releases fit. warnManifest comes about 27 releases before the limit, time
// to leave the oldest releases out (docs/releasing.md).
const (
	maxManifest  = 8 << 20
	warnManifest = 6 << 20
)

// checkSize refuses a manifest no kvsctl would read, and warns while there
// is still room.
func checkSize(size, releases int) error {
	perRelease := size / max(releases, 1)
	if size > maxManifest {
		return fmt.Errorf("the manifest would be %s for %d releases, and kvsctl reads at most %s: leave the oldest releases out of it first (docs/releasing.md)",
			mebibytes(size), releases, mebibytes(maxManifest))
	}
	if size > warnManifest {
		warn("the manifest is %s of the %s kvsctl reads: at %d kB per release, about %d more releases fit before the oldest ones have to leave it (docs/releasing.md)",
			mebibytes(size), mebibytes(maxManifest), perRelease/1000, (maxManifest-size)/max(perRelease, 1))
	}
	return nil
}

func mebibytes(n int) string {
	return strconv.FormatFloat(float64(n)/(1<<20), 'f', 1, 64) + " MiB"
}

// warn prints a warning on stderr. Inside a GitHub workflow it is an
// annotation, which shows on the page of the run instead of only deep in
// the log of a step nobody reads when it succeeds.
func warn(format string, args ...any) {
	prefix := "kvsctl-release: warning: "
	if os.Getenv("GITHUB_ACTIONS") == "true" {
		prefix = "::warning::"
	}
	fmt.Fprintf(os.Stderr, prefix+format+"\n", args...)
}

// sumsFile is the checksum list the release publishes beside the binaries,
// in the format sha256sum writes.
const sumsFile = "SHA256SUMS"

// publishedSums reads the SHA256SUMS of the assets directory, file name to
// sha256, or nil when there is no such directory or file.
func publishedSums(assets string) (map[string]string, error) {
	if assets == "" {
		return nil, nil
	}
	data, err := os.ReadFile(filepath.Join(assets, sumsFile))
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	sums := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		if len(fields) != 2 || len(fields[0]) != 64 {
			return nil, fmt.Errorf("%s: %q is not a line of sha256sum", filepath.Join(assets, sumsFile), line)
		}
		// sha256sum marks a file it read in binary mode with a star.
		sums[strings.TrimPrefix(fields[1], "*")] = fields[0]
	}
	return sums, nil
}

func slicesContains(list []string, want string) bool {
	for _, item := range list {
		if item == want {
			return true
		}
	}
	return false
}

// assetSum is the sha256 and the size of a file named in --cli, computed
// from the copy in the assets directory when one is given (the release
// assets are local when the manifest is signed). The manifest signs the
// size beside the sum, a bound a download of the build can stop at
// (release.DownloadSized). Without the assets directory the sum is read
// from url+.sha256 and the size is unknown, 0, which leaves such a
// download to its own bound.
func assetSum(url, assets string) (string, int64, error) {
	if assets != "" {
		local := filepath.Join(assets, filepath.Base(url))
		sum, size, err := fileSum(local)
		if err != nil {
			return "", 0, fmt.Errorf("asset of %s: %w", url, err)
		}
		return sum, size, nil
	}
	shaBytes, err := readURL(url + ".sha256")
	if err != nil {
		return "", 0, fmt.Errorf("%s.sha256: %w", url, err)
	}
	parts := strings.Fields(string(shaBytes))
	if len(parts) == 0 || len(parts[0]) != 64 {
		return "", 0, fmt.Errorf("%s.sha256 holds no sha256", url)
	}
	return parts[0], 0, nil
}

func readURL(url string) ([]byte, error) {
	if strings.HasPrefix(url, "file://") {
		return os.ReadFile(strings.TrimPrefix(url, "file://"))
	}
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: %s", url, resp.Status)
	}
	return io.ReadAll(resp.Body)
}

// verify checks a manifest file against its signature file with the public
// keys given, which is what the release workflow does with the previous
// manifest before building the next one on it, and with the new one before
// publishing it. kvsctl accepts a manifest as soon as one signature matches
// a key it embeds; --all is stricter and wants every signature to match,
// which proves that each key the workflow signed with is a key the shipped
// kvsctl trusts, the next key of a rotation included.
func verify(args []string) error {
	fs := flag.NewFlagSet("verify", flag.ExitOnError)
	var pubs stringList
	manifestPath := fs.String("manifest", "", "manifest.json")
	sigPath := fs.String("signature", "", "manifest.json.sig")
	fs.Var(&pubs, "pub", "public key, base64 or id=base64; repeat it, one match is enough")
	all := fs.Bool("all", false, "every signature of the file must match one of the keys, not just one")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *manifestPath == "" || *sigPath == "" || len(pubs) == 0 {
		return errors.New("verify needs --manifest, --signature and at least one --pub")
	}
	raw, err := os.ReadFile(*manifestPath)
	if err != nil {
		return err
	}
	sig, err := os.ReadFile(*sigPath)
	if err != nil {
		return err
	}
	keys, err := manifest.ParseKeys(pubs)
	if err != nil {
		return err
	}
	doc, err := manifest.Load(raw, sig)
	if err != nil {
		return err
	}
	if *all {
		for n, s := range doc.Signatures {
			one := &manifest.Document{Raw: raw, Signatures: []manifest.Signature{s}}
			if err := one.VerifyAny(keys); err != nil {
				return fmt.Errorf("signature %d of %d: %w", n+1, len(doc.Signatures), err)
			}
		}
	}
	if err := doc.VerifyAny(keys); err != nil {
		return err
	}
	fmt.Printf("%s verified: schema %d, %d releases, latest %s, updated %s\n", *manifestPath, doc.Manifest.Schema, len(doc.Manifest.Releases), doc.Manifest.Latest().Version, doc.Manifest.Updated)
	return nil
}
