#!/bin/bash
# .github/scripts/release-images.sh turns what the images job of the release
# workflow built, plus docker/images.lock, into the arguments of
# kvsctl-release. Every image the repository builds comes with the digest the
# build reported, php-fpm and cron once per PHP series, MariaDB once per
# series of the lock (a stack keeps its series), and the other images the
# stack runs with the digest the lock pins. A lock without MariaDB, a series
# that is not major.minor, or a missing or empty digest stops the release.
set -euo pipefail
ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
SCRIPT="$ROOT_DIR/.github/scripts/release-images.sh"
TEST_DIR=$(mktemp -d "${TMPDIR:-/tmp}/kvs-release-images.XXXXXX")
trap 'rm -rf "$TEST_DIR"' EXIT
fail() { echo "FAIL: $*" >&2; exit 1; }

# A digest that is unique per number and of low entropy.
digest() { printf 'sha256:%064d' "$1"; }

# The lock lists the MariaDB series out of order, as a hand edit of
# resolve-bases.sh could; the release publishes them oldest first.
write_lock() {
    {
        printf '# Generated by docker/bin/resolve-bases.sh. Do not edit by hand.\n\n'
        printf '# Build bases\n'
        printf 'php-fpm\t8.1\tphp:8.1-fpm@%s\n' "$(digest 1)"
        printf 'php-cli\t8.1\tphp:8.1-cli@%s\n' "$(digest 2)"
        printf 'nginx\t-\tnginx:mainline@%s\n' "$(digest 3)"
        printf '\n# Images the compose file runs unchanged\n'
        printf 'mariadb\t11.8\tmariadb:11.8.9@%s\n' "$(digest 11)"
        printf 'mariadb\t12.3\tmariadb:12.3.1@%s\n' "$(digest 12)"
        printf 'mariadb\t11.4\tmariadb:11.4.13@%s\n' "$(digest 13)"
        printf 'memcached\t-\tmemcached:1.6.45-alpine@%s\n' "$(digest 14)"
        printf 'dragonfly\t-\tdocker.dragonflydb.io/dragonflydb/dragonfly:v1.35.1@%s\n' "$(digest 15)"
        printf 'acme\t-\tneilpang/acme.sh:3.1.6@%s\n' "$(digest 16)"
        printf 'alpine\t-\talpine:3.24.2@%s\n' "$(digest 17)"
    } > "$1"
}

# One file per image the images job built, named and written the way its
# "record the digest" step does.
write_digests() {
    mkdir -p "$1"
    printf 'nginx=%s\n' "$(digest 21)" > "$1/nginx.txt"
    printf 'kvs-init=%s\n' "$(digest 22)" > "$1/kvs-init.txt"
    printf 'manticore=%s\n' "$(digest 23)" > "$1/manticore.txt"
    printf 'php-fpm@8.1=%s\n' "$(digest 24)" > "$1/php-fpm8.1.txt"
    printf 'php-fpm@8.4=%s\n' "$(digest 25)" > "$1/php-fpm8.4.txt"
    printf 'cron@8.1=%s\n' "$(digest 26)" > "$1/cron8.1.txt"
    printf 'cron@8.4=%s\n' "$(digest 27)" > "$1/cron8.4.txt"
}

run_script() {
    IMAGES_LOCK="$1" "$SCRIPT" ghcr.io/example/kvs-install 26.11.0 "$2" "$3"
}

write_lock "$TEST_DIR/images.lock"
write_digests "$TEST_DIR/digests"
run_script "$TEST_DIR/images.lock" "$TEST_DIR/digests" "$TEST_DIR/out" > "$TEST_DIR/out.log" ||
    fail "the script refused a complete lock and digests: $(cat "$TEST_DIR/out.log")"

ns=ghcr.io/example/kvs-install
expected_images="nginx=$ns/nginx:26.11.0,kvs-init=$ns/init:26.11.0,manticore=$ns/manticore:26.11.0"
expected_images+=",cron@8.1=$ns/cron:26.11.0-php8.1,cron@8.4=$ns/cron:26.11.0-php8.4"
expected_images+=",php-fpm@8.1=$ns/php:26.11.0-php8.1,php-fpm@8.4=$ns/php:26.11.0-php8.4"
expected_images+=",mariadb@11.4=mariadb:11.4.13,mariadb@11.8=mariadb:11.8.9,mariadb@12.3=mariadb:12.3.1"
expected_images+=",memcached=memcached:1.6.45-alpine,dragonfly=docker.dragonflydb.io/dragonflydb/dragonfly:v1.35.1"
expected_images+=",acme=neilpang/acme.sh:3.1.6,phpmyadmin-init=alpine:3.24.2"
[ "$(cat "$TEST_DIR/out/images.spec")" = "$expected_images" ] ||
    fail "images.spec is '$(cat "$TEST_DIR/out/images.spec")', expected '$expected_images'"

expected_digests="nginx=$(digest 21),kvs-init=$(digest 22),manticore=$(digest 23)"
expected_digests+=",cron@8.1=$(digest 26),cron@8.4=$(digest 27),php-fpm@8.1=$(digest 24),php-fpm@8.4=$(digest 25)"
expected_digests+=",mariadb@11.4=$(digest 13),mariadb@11.8=$(digest 11),mariadb@12.3=$(digest 12)"
expected_digests+=",memcached=$(digest 14),dragonfly=$(digest 15),acme=$(digest 16),phpmyadmin-init=$(digest 17)"
[ "$(cat "$TEST_DIR/out/digests.spec")" = "$expected_digests" ] ||
    fail "digests.spec is '$(cat "$TEST_DIR/out/digests.spec")', expected '$expected_digests'"

[ "$(cat "$TEST_DIR/out/php-series.spec")" = "8.1,8.4" ] ||
    fail "php-series.spec is '$(cat "$TEST_DIR/out/php-series.spec")', expected '8.1,8.4'"
[ ! -e "$TEST_DIR/out/mariadb-from.spec" ] ||
    fail "mariadb-from.spec is written although kvsctl-release no longer takes --mariadb-from"
grep -Fqx 'mariadb series: 11.4,11.8,12.3' "$TEST_DIR/out.log" ||
    fail "the log does not list the published MariaDB series: $(cat "$TEST_DIR/out.log")"
echo "PASS: every MariaDB series of the lock is published as a variant, with its digest"

# The refusals, each from a copy of the good input with one defect.
refused() {
    local name=$1 lock=$2 digests=$3 want=$4 status=0
    run_script "$lock" "$digests" "$TEST_DIR/refused-out" > "$TEST_DIR/refused.log" 2>&1 || status=$?
    [ "$status" -ne 0 ] || fail "$name was accepted"
    grep -Fq "$want" "$TEST_DIR/refused.log" ||
        fail "$name: the message does not say '$want': $(cat "$TEST_DIR/refused.log")"
}

grep -v '^mariadb' "$TEST_DIR/images.lock" > "$TEST_DIR/no-mariadb.lock"
refused "a lock without MariaDB" "$TEST_DIR/no-mariadb.lock" "$TEST_DIR/digests" "pins no MariaDB series"

awk -F '\t' 'BEGIN { OFS = "\t" } $1 == "mariadb" && $2 == "11.4" { $2 = "-" } { print }' \
    "$TEST_DIR/images.lock" > "$TEST_DIR/bad-series.lock"
refused "a MariaDB entry without a series" "$TEST_DIR/bad-series.lock" "$TEST_DIR/digests" "is not major.minor"

cp -r "$TEST_DIR/digests" "$TEST_DIR/no-nginx"
rm "$TEST_DIR/no-nginx/nginx.txt"
refused "a build without the nginx digest" "$TEST_DIR/images.lock" "$TEST_DIR/no-nginx" "no digest recorded for nginx"

cp -r "$TEST_DIR/digests" "$TEST_DIR/empty-digest"
printf 'php-fpm@8.1=\n' > "$TEST_DIR/empty-digest/php-fpm8.1.txt"
refused "an empty PHP variant digest" "$TEST_DIR/images.lock" "$TEST_DIR/empty-digest" "empty digest for php-fpm@8.1"

cp -r "$TEST_DIR/digests" "$TEST_DIR/no-php"
rm "$TEST_DIR/no-php/"php-fpm*.txt "$TEST_DIR/no-php/"cron*.txt
refused "a build without PHP variants" "$TEST_DIR/images.lock" "$TEST_DIR/no-php" "no PHP variant image was recorded"

grep -v '^memcached' "$TEST_DIR/images.lock" > "$TEST_DIR/no-memcached.lock"
refused "a lock without memcached" "$TEST_DIR/no-memcached.lock" "$TEST_DIR/digests" "no entry for memcached"

# A stack runs php-fpm and cron of one PHP series: a series built for only
# one of them would be refused when the manifest is signed.
cp -r "$TEST_DIR/digests" "$TEST_DIR/no-cron-8.4"
rm "$TEST_DIR/no-cron-8.4/cron8.4.txt"
refused "a PHP series without its cron image" "$TEST_DIR/images.lock" "$TEST_DIR/no-cron-8.4" "PHP 8.4 has a php-fpm image but no cron image"
cp -r "$TEST_DIR/digests" "$TEST_DIR/no-fpm-8.1"
rm "$TEST_DIR/no-fpm-8.1/php-fpm8.1.txt"
refused "a PHP series without its php-fpm image" "$TEST_DIR/images.lock" "$TEST_DIR/no-fpm-8.1" "PHP 8.1 has a cron image but no php-fpm image"
cp -r "$TEST_DIR/digests" "$TEST_DIR/no-cron"
rm "$TEST_DIR/no-cron/"cron*.txt
refused "a build without any cron image" "$TEST_DIR/images.lock" "$TEST_DIR/no-cron" "no cron image"
echo "PASS: a lock or a build that misses an image stops the release"

# The images the script names cover the services of the compose file, no
# more and no fewer: kvsctl-release bundle refuses any other list, and this
# finds it on the pull request instead of in the publish job.
compose_services=$(awk '
    /^[^ #]/ { in_services = ($0 ~ /^services:/); next }
    in_services && /^  [A-Za-z0-9][A-Za-z0-9_.-]*:[ \t]*(#.*)?$/ { sub(/^  /, ""); sub(/:.*/, ""); print }
' "$ROOT_DIR/docker/docker-compose.yml" | sort -u)
spec_services=$(tr ',' '\n' < "$TEST_DIR/out/images.spec" | sed 's/[@=].*//' | sort -u)
[ -n "$compose_services" ] || fail "no service read from docker/docker-compose.yml"
[ "$compose_services" = "$spec_services" ] ||
    fail "release-images.sh names $(paste -sd' ' <<<"$spec_services"), docker/docker-compose.yml runs $(paste -sd' ' <<<"$compose_services")"
echo "PASS: the release images cover every service of the compose file"
