package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/MaximeMichaud/KVS-install/cli/internal/instance"
	"github.com/MaximeMichaud/KVS-install/cli/internal/runlog"
)

func writeOverride(t *testing.T, stateDir, version string, images map[string]string) {
	t.Helper()
	dir := filepath.Join(stateDir, "releases", version, "docker")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	body := "# Generated by kvsctl-release for stack " + version + "\nservices:\n"
	for _, service := range []string{"nginx", "php-fpm"} {
		if ref, ok := images[service]; ok {
			body += "  " + service + ":\n    image: \"" + ref + "\"\n"
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "docker-compose.release.yml"), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestRefsFromOverride(t *testing.T) {
	stateDir := t.TempDir()
	writeOverride(t, stateDir, "0.2.0", map[string]string{"nginx": "ghcr.io/x/nginx:0.2.0", "php-fpm": "ghcr.io/x/php:0.2.0"})
	refs, err := refsFromOverride(filepath.Join(stateDir, "releases", "0.2.0", "docker", "docker-compose.release.yml"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Join(refs, " ") != "ghcr.io/x/nginx:0.2.0 ghcr.io/x/php:0.2.0" {
		t.Fatalf("refs are %v", refs)
	}
	missing, err := refsFromOverride(filepath.Join(stateDir, "releases", "9.9.9", "docker", "docker-compose.release.yml"))
	if err != nil || missing != nil {
		t.Fatalf("a missing override gave %v, %v", missing, err)
	}
}

// TestCleanTargets checks the two rules that matter: the current and the
// previous version stay, and an image several versions share is kept as
// long as one of those two pins it.
func TestCleanTargets(t *testing.T) {
	stateDir := t.TempDir()
	writeOverride(t, stateDir, "0.1.0", map[string]string{"nginx": "ghcr.io/x/nginx:0.1.0", "php-fpm": "ghcr.io/x/php:0.1.0"})
	writeOverride(t, stateDir, "0.2.0", map[string]string{"nginx": "ghcr.io/x/nginx:shared", "php-fpm": "ghcr.io/x/php:0.2.0"})
	writeOverride(t, stateDir, "0.3.0", map[string]string{"nginx": "ghcr.io/x/nginx:shared", "php-fpm": "ghcr.io/x/php:0.3.0"})
	// 0.0.9 is only in the history: its files are already gone, and so is
	// anything kvsctl could have known about its images.
	downloads := filepath.Join(stateDir, "downloads")
	if err := os.MkdirAll(downloads, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(downloads, "kvs-stack-0.3.0.tar.gz"), []byte("bundle"), 0o600); err != nil {
		t.Fatal(err)
	}
	state := &instance.State{
		Current:  "0.3.0",
		Previous: "0.2.0",
		History: []instance.Entry{
			{Version: "0.0.9", Action: "adopt"},
			{Version: "0.1.0", Action: "upgrade"},
		},
	}
	plan, err := cleanTargets(stateDir, state)
	if err != nil {
		t.Fatal(err)
	}
	if got := strings.Join(plan.Images, " "); got != "ghcr.io/x/nginx:0.1.0 ghcr.io/x/php:0.1.0" {
		t.Fatalf("images to remove are %q", got)
	}
	if len(plan.Releases) != 1 || filepath.Base(plan.Releases[0]) != "0.1.0" {
		t.Fatalf("release directories are %v", plan.Releases)
	}
	if plan.Downloads != downloads {
		t.Fatalf("downloads are %q", plan.Downloads)
	}
	if strings.Join(plan.Kept, " ") != "0.2.0 0.3.0" {
		t.Fatalf("kept versions are %v", plan.Kept)
	}
	if summary := cleanSummary(plan); summary != "2 images, 1 kept release, the downloaded bundles" {
		t.Fatalf("summary is %q", summary)
	}
}

// TestCleanTargetsWithoutState keeps every version: nothing says which
// images a rollback still needs.
func TestCleanTargetsWithoutState(t *testing.T) {
	stateDir := t.TempDir()
	writeOverride(t, stateDir, "0.1.0", map[string]string{"nginx": "ghcr.io/x/nginx:0.1.0"})
	downloads := filepath.Join(stateDir, "downloads")
	if err := os.MkdirAll(downloads, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(downloads, "bundle.tar.gz"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	plan, err := cleanTargets(stateDir, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Images) != 0 || len(plan.Releases) != 0 {
		t.Fatalf("an unadopted stack would lose %v and %v", plan.Images, plan.Releases)
	}
	if plan.Downloads != downloads {
		t.Fatalf("downloads are %q", plan.Downloads)
	}
}

func TestOnlyLocal(t *testing.T) {
	got := onlyLocal([]string{"a:1", "b:1"}, []string{"b:1", "c:1"})
	if strings.Join(got, " ") != "b:1" {
		t.Fatalf("kept %v", got)
	}
}

func TestDirSize(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "a"), make([]byte, 100), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "sub"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "sub", "b"), make([]byte, 50), 0o600); err != nil {
		t.Fatal(err)
	}
	if size := dirSize(dir); size != 150 {
		t.Fatalf("size is %d, wanted 150", size)
	}
}

func TestImageCandidates(t *testing.T) {
	cases := map[string]string{
		"ghcr.io/x/php:0.3.0@sha256:abc":                    "ghcr.io/x/php:0.3.0 ghcr.io/x/php@sha256:abc",
		"127.0.0.1:5000/kvs-install/nginx:0.2.0@sha256:f3d": "127.0.0.1:5000/kvs-install/nginx:0.2.0 127.0.0.1:5000/kvs-install/nginx@sha256:f3d",
		"ghcr.io/x/php@sha256:abc":                          "ghcr.io/x/php@sha256:abc",
		"ghcr.io/x/php:0.3.0":                               "ghcr.io/x/php:0.3.0",
		"${KVS_PHP_FPM_IMAGE}":                              "",
	}
	for ref, want := range cases {
		if got := strings.Join(imageCandidates(ref), " "); got != want {
			t.Errorf("imageCandidates(%q) = %q, want %q", ref, got, want)
		}
	}
}

// The pins recorded by an upgrade name the variant images, which the
// override only reads from .env, and a pin shared with a kept version stays
// under every form the engine lists it by.
func TestCleanTargetsUsesTheRecordedPins(t *testing.T) {
	stateDir := t.TempDir()
	state := &instance.State{
		Current:  "0.2.0",
		Previous: "0.1.0",
		ReleaseImages: map[string][]string{
			"0.2.0": {"r/nginx:0.2.0@sha256:n2", "r/php:0.2.0@sha256:p2"},
			"0.3.0": {"r/nginx:0.2.0@sha256:n2", "r/php:0.3.0@sha256:p3"},
		},
	}
	plan, err := cleanTargets(stateDir, state)
	if err != nil {
		t.Fatal(err)
	}
	if got := strings.Join(plan.Images, " "); got != "r/php:0.3.0 r/php@sha256:p3" {
		t.Fatalf("images to remove are %q", got)
	}
	if strings.Join(plan.Dropped, " ") != "0.3.0" {
		t.Fatalf("dropped versions are %v", plan.Dropped)
	}
	local := []string{"r/php:0.3.0", "r/nginx:0.2.0", "r/php:0.2.0"}
	if got := strings.Join(onlyLocal(plan.Images, local), " "); got != "r/php:0.3.0" {
		t.Fatalf("the engine holds %q of those", got)
	}
}

// cleanRoot is a stack on 1.2.0, previous 1.1.0, that keeps the release
// files of 1.0.0 and downloaded bundles, which clean removes; the engine
// holds no image of 1.0.0.
func cleanRoot(t *testing.T) (root string, inst *instance.Instance) {
	t.Helper()
	root = newRoot(t, "docker/.env", "DOMAIN=example.com\nCOMPOSE_PROJECT_NAME=site\nSITE_PREFIX=site\n")
	inst = saveState(t, root, &instance.State{Current: "1.2.0", Previous: "1.1.0", History: []instance.Entry{{Version: "1.0.0", Action: "adopt"}}})
	for _, name := range []string{"releases/1.0.0/docker/docker-compose.yml", "downloads/kvs-stack-1.2.0.tar.gz"} {
		path := filepath.Join(inst.StateDir(), name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(strings.Repeat("x", 1000)), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	fakeEngine(t, "site", func() []engineContainer { return nil })
	return root, inst
}

// With --quiet a clean that worked prints nothing: what it removed goes to
// the log. A dry run still prints its list, which it was run for; without
// --quiet, clean says what it removes and what it reclaimed.
func TestQuietCleanPrintsNothing(t *testing.T) {
	root, inst := cleanRoot(t)
	useRoot(t, root)
	useStderr(t)
	out, err := runKvsctl(t, "clean", "--root", root, "--yes", "--quiet", "--dry-run")
	if err != nil || !strings.Contains(out, "Release files:\n") || !strings.Contains(out, "nothing removed (--dry-run)\n") {
		t.Fatalf("a quiet dry run: %v, printed %q", err, out)
	}
	// clean is registered once, so its --dry-run keeps the value of the
	// run before unless it is given.
	out, err = runKvsctl(t, "clean", "--root", root, "--yes", "--quiet", "--dry-run=false")
	if err != nil || out != "" {
		t.Fatalf("a quiet clean: %v, printed %q", err, out)
	}
	if _, err := os.Stat(filepath.Join(inst.StateDir(), "releases", "1.0.0")); !os.IsNotExist(err) {
		t.Fatalf("the files of 1.0.0 are still there: %v", err)
	}
	logs, err := runlog.List(inst.StateDir())
	if err != nil || len(logs) == 0 {
		t.Fatalf("no log: %v", err)
	}
	data, err := os.ReadFile(logs[0])
	if err != nil || !strings.Contains(string(data), "removed "+filepath.Join(inst.StateDir(), "releases", "1.0.0")) || !strings.Contains(string(data), "reclaimed") {
		t.Fatalf("the log lacks what clean removed (%v):\n%s", err, data)
	}
	out, err = runKvsctl(t, "clean", "--root", root, "--yes", "--dry-run=false")
	if err != nil || !strings.HasSuffix(out, "\nnothing to clean\n") {
		t.Fatalf("a clean with nothing left: %v, printed %q", err, out)
	}
	out, err = runKvsctl(t, "clean", "--root", root, "--yes", "--quiet", "--dry-run=false")
	if err != nil || out != "" {
		t.Fatalf("a quiet clean with nothing left: %v, printed %q", err, out)
	}
}

// With --quiet a clean that removes images prints nothing either, and one
// whose images the engine no longer holds has nothing to clean, which it
// does not say; without --quiet it says both.
func TestQuietCleanOfImages(t *testing.T) {
	root := newRoot(t, "docker/.env", "DOMAIN=example.com\nCOMPOSE_PROJECT_NAME=site\nSITE_PREFIX=site\n")
	useRoot(t, root)
	useStderr(t)
	const old = "example/nginx:1.0.0"
	state := func() *instance.State {
		return &instance.State{Current: "1.2.0", Previous: "1.1.0", ReleaseImages: map[string][]string{"1.0.0": {old}}}
	}
	inst := saveState(t, root, state())
	fakeEngine(t, "site", func() []engineContainer { return nil }, engineImage{tags: []string{old}})
	out, err := runKvsctl(t, "clean", "--root", root, "--yes", "--quiet", "--dry-run=false")
	if err != nil || out != "" {
		t.Fatalf("a quiet clean of an image: %v, printed %q", err, out)
	}
	if recorded := loadState(t, root).ReleaseImages["1.0.0"]; recorded != nil {
		t.Fatalf("the images of 1.0.0 are still recorded: %v", recorded)
	}
	logs, err := runlog.List(inst.StateDir())
	if err != nil || len(logs) == 0 {
		t.Fatalf("no log: %v", err)
	}
	if data, err := os.ReadFile(logs[0]); err != nil || !strings.Contains(string(data), "removed "+old) {
		t.Fatalf("the log lacks the image clean removed (%v):\n%s", err, data)
	}

	// The engine no longer holds the image the state still records.
	saveState(t, root, state())
	fakeEngine(t, "site", func() []engineContainer { return nil })
	out, err = runKvsctl(t, "clean", "--root", root, "--yes", "--quiet", "--dry-run=false")
	if err != nil || out != "" {
		t.Fatalf("a quiet clean of an image the engine no longer holds: %v, printed %q", err, out)
	}
	out, err = runKvsctl(t, "clean", "--root", root, "--yes", "--dry-run=false")
	if err != nil || !strings.HasSuffix(out, "\nnothing to clean\n") {
		t.Fatalf("a clean of an image the engine no longer holds: %v, printed %q", err, out)
	}
}

// A clean whose removals did not all work exits 1 after a change: its
// message says what it reclaimed, which --quiet printed nothing of.
func TestCleanSaysWhatItReclaimedWhenARemovalFails(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root removes files from a read-only directory")
	}
	root, inst := cleanRoot(t)
	useRoot(t, root)
	useStderr(t)
	releases := filepath.Join(inst.StateDir(), "releases")
	if err := os.Chmod(releases, 0o500); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(releases, 0o755) })
	out, err := runKvsctl(t, "clean", "--root", root, "--yes", "--quiet", "--dry-run=false")
	if err == nil || !strings.HasPrefix(err.Error(), "1 kB reclaimed, but 1 removal failed: ") || !strings.Contains(err.Error(), filepath.Join(releases, "1.0.0")) || exitCode(err) != exitError || out != "" {
		t.Fatalf("a clean whose removal failed: %v, printed %q", err, out)
	}
}
