name: Test KVS Installation on Debian and Ubuntu

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os-php:
          - os: debian:11
            php: '7.4'
          - os: debian:11
            php: '8.1'
          - os: debian:12
            php: '7.4'
          - os: debian:12
            php: '8.1'
          - os: ubuntu:20.04
            php: '7.4'
          - os: ubuntu:20.04
            php: '8.1'
          - os: ubuntu:22.04
            php: '7.4'
          - os: ubuntu:22.04
            php: '8.1'

    container:
      image: ${{ matrix.os-php.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install prerequisites
      run: |
        apt-get update
        apt-get install -y curl wget
      shell: bash

    - name: Download and execute the KVS installation script
      run: |
        wget https://raw.githubusercontent.com/MaximeMichaud/KVS-install/main/kvs-install.sh
        chmod +x kvs-install.sh
        CI_MODE='y' \
        PHP='${{ matrix.os-php.php }}' \
        database_ver='10.11' \
        IONCUBE='YES' \
        AUTOPACKAGEUPDATE='YES' \
        ./kvs-install.sh
      shell: bash

    - name: Check service versions
      run: |
        mariadb --version
        nginx -v
        memcached --version
        php -v
      shell: bash
