name: Test KVS Installation on Debian 11 and 12

on:
  push:
    branches:
      - '*'   
  pull_request:
    branches:
      - '*'   

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['debian:11', 'debian:12']

    container:
      image: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install curl and prerequisites
      run: |
        apt-get update
        apt-get install -y curl
      shell: bash

    - name: Run KVS Installation Script
      run: |
        export CI_MODE='y'
        export PHP='7.4'
        bash <(curl -s https://raw.githubusercontent.com/MaximeMichaud/KVS-install/main/kvs-install.sh)
      shell: bash

    - name: Check service statuses and logs
      run: |
        systemctl status mariadb
        systemctl status nginx
        echo "Check log file for any issues:"
        cat kvs-install.log
      shell: bash
