name: Test KVS Installation on Debian 11 and 12

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['debian:11', 'debian:12']

    container:
      image: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install prerequisites
      run: |
        apt-get update
        apt-get install -y curl wget
      shell: bash

    - name: Download and execute the KVS installation script
      run: |
        wget https://raw.githubusercontent.com/MaximeMichaud/KVS-install/main/kvs-install.sh
        chmod +x kvs-install.sh
        CI_MODE='y' \
        PHP='7.4' \
        database_ver='10.11' \
        IONCUBE='YES' \
        AUTOPACKAGEUPDATE='YES' \
        ./kvs-install.sh
      shell: bash

    - name: Check service versions
      run: |
        mariadb --version
        nginx -v
        memcached --version
        php -v
        echo "Check log file for any issues:"
        cat /root/kvs-install.log
      shell: bash
